services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: authorizationPgDb
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: app123
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"

volumes:
  pgdata: